import 'dotenv/config';
import express from 'express'; import cors from 'cors'; import mongoose from 'mongoose'; import fs from 'node:fs/promises'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import multer from 'multer'; import rateLimit from 'express-rate-limit'; import crypto from 'node:crypto';
const app=express(), port=process.env.PORT||5000, base=path.dirname(fileURLToPath(import.meta.url)), dataFile=path.resolve(base,'../data.json');
app.use(cors({origin:process.env.CLIENT_URL||'http://localhost:5173'})); app.use(express.json({limit:'2mb'})); app.use('/uploads',express.static(path.resolve(base,'../uploads')));
const schemas={users:new mongoose.Schema({name:String,email:{type:String,unique:true},password:String,role:{type:String,default:'Author'},active:{type:Boolean,default:true}}, {timestamps:true}),pages:new mongoose.Schema({title:String,slug:String,status:{type:String,default:'draft'},sections:Array,seo:Object,author:String},{timestamps:true}),posts:new mongoose.Schema({title:String,slug:String,excerpt:String,content:String,status:{type:String,default:'draft'},category:String,tags:[String],featuredImage:String,seo:Object,publishAt:Date,author:String,views:{type:Number,default:0}},{timestamps:true}),categories:new mongoose.Schema({name:String,slug:String,description:String},{timestamps:true}),media:new mongoose.Schema({filename:String,url:String,mimetype:String,size:Number,alt:String},{timestamps:true}),contacts:new mongoose.Schema({name:String,email:String,phone:String,message:String,status:{type:String,default:'new'}},{timestamps:true}),logs:new mongoose.Schema({workflow:String,trigger:String,status:String,result:String,error:String,startedAt:Date,completedAt:Date},{timestamps:true}),settings:new mongoose.Schema({key:{type:String,unique:true},value:mongoose.Schema.Types.Mixed})};
const models=Object.fromEntries(Object.entries(schemas).map(([k,s])=>[k,mongoose.model(k,s)])); let mongoReady=false;
mongoose.connect(process.env.MONGODB_URI||'').then(()=>{mongoReady=true;console.log('MongoDB connected')}).catch(()=>console.log('MongoDB unavailable; using local demo store'));
let store={users:[],pages:[],posts:[],categories:[],media:[],contacts:[],logs:[],settings:[]};
async function load(){try{store=JSON.parse(await fs.readFile(dataFile,'utf8'))}catch{await save()}} async function save(){await fs.mkdir(path.dirname(dataFile),{recursive:true});await fs.writeFile(dataFile,JSON.stringify(store,null,2))} await load();
const repo={async all(k,filter={}){if(mongoReady)return models[k].find(filter).sort({createdAt:-1}).lean();return store[k].filter(x=>Object.entries(filter).every(([a,b])=>x[a]===b))},async one(k,id){if(mongoReady)return models[k].findById(id).lean();return store[k].find(x=>x._id===id)},async create(k,obj){if(mongoReady)return new models[k](obj).save().then(x=>x.toObject());const x={_id:crypto.randomUUID(),createdAt:new Date(),updatedAt:new Date(),...obj};store[k].unshift(x);await save();return x},async update(k,id,obj){if(mongoReady)return models[k].findByIdAndUpdate(id,obj,{new:true}).lean();const x=store[k].find(x=>x._id===id);if(!x)return null;Object.assign(x,obj,{updatedAt:new Date()});await save();return x},async del(k,id){if(mongoReady)return models[k].findByIdAndDelete(id);store[k]=store[k].filter(x=>x._id!==id);await save()}};
const token=u=>jwt.sign({id:u._id,role:u.role,name:u.name},process.env.JWT_SECRET||'demo-secret', {expiresIn:'7d'}); const auth=(req,res,next)=>{try{const t=(req.headers.authorization||'').replace('Bearer ','');req.user=jwt.verify(t,process.env.JWT_SECRET||'demo-secret');next()}catch{return res.status(401).json({error:'Please sign in to continue'})}}; const role=(...rs)=>(req,res,next)=>rs.includes(req.user.role)?next():res.status(403).json({error:'Your role cannot perform this action'});
const asyncRoute=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
async function log(workflow,trigger,result,status='Success',error=''){return repo.create('logs',{workflow,trigger,result,status,error,startedAt:new Date(),completedAt:new Date()})}
async function emit(event,payload){const paths={'contact-submission':'contact-submission','blog-published':'blog-published','user-registered':'user-registered'},workflow=event==='contact-submission'?'Contact Notification':event==='blog-published'?'Blog Published':'Welcome User';let result='Demo workflow executed; notification recorded locally.',status='Success',error='';if(process.env.N8N_BASE_URL){try{const response=await fetch(`${process.env.N8N_BASE_URL.replace(/\/$/,'')}/webhook/flowcms/${paths[event]}`,{method:'POST',headers:{'content-type':'application/json','x-flowcms-secret':process.env.N8N_WEBHOOK_SECRET||''},body:JSON.stringify(payload),signal:AbortSignal.timeout(5000)});if(!response.ok)throw Error(`n8n returned ${response.status}`);result=await response.text()||'n8n workflow completed';}catch(e){status='Failed';error=e.message;result=''}}return log(workflow,'Webhook',result,status,error)}
app.post('/api/auth/register',rateLimit({windowMs:60000,max:8}),asyncRoute(async(req,res)=>{const{name,email,password}=req.body;if(!name||!email||!password||password.length<8)return res.status(400).json({error:'Name, email and password (8+ characters) are required'});if((await repo.all('users')).some(u=>u.email===email.toLowerCase()))return res.status(409).json({error:'Email already registered'});const u=await repo.create('users',{name,email:email.toLowerCase(),password:await bcrypt.hash(password,10),role:'Author',active:true});emit('user-registered',{name,email:u.email}).catch(()=>{});res.status(201).json({token:token(u),user:{...u,password:undefined}})}));
app.post('/api/auth/login',rateLimit({windowMs:60000,max:12}),asyncRoute(async(req,res)=>{const u=(await repo.all('users')).find(x=>x.email===String(req.body.email||'').toLowerCase()&&x.active!==false);if(!u||!await bcrypt.compare(req.body.password||'',u.password))return res.status(401).json({error:'Invalid email or password'});res.json({token:token(u),user:{...u,password:undefined}})})); app.get('/api/auth/me',auth,asyncRoute(async(req,res)=>{const u=await repo.one('users',req.user.id);if(!u)return res.status(401).json({error:'User not found'});res.json({user:{...u,password:undefined}})}));
function resource(route,key,writeRoles=['Super Admin','Editor']){app.get(`/api/${route}`,auth,asyncRoute(async(req,res)=>{if(key==='users'&&req.user.role!=='Super Admin')return res.status(403).json({error:'Only Super Admins can manage users'});let rows=await repo.all(key);if(key==='posts'&&req.user.role==='Author')rows=rows.filter(p=>p.authorId===req.user.id);const q=String(req.query.search||'').toLowerCase();if(q)rows=rows.filter(x=>JSON.stringify(x).toLowerCase().includes(q));if(key==='users')rows=rows.map(({password,...u})=>u);res.json(rows)}));app.post(`/api/${route}`,auth,role(...writeRoles),asyncRoute(async(req,res)=>{let payload={...req.body,authorId:req.user.id,author:req.user.name};if(key==='users'){if(!payload.name||!payload.email||!payload.password||payload.password.length<8)return res.status(400).json({error:'Name, email and password (8+ characters) are required'});payload.email=payload.email.toLowerCase();payload.password=await bcrypt.hash(payload.password,10);if(!['Super Admin','Editor','Author'].includes(payload.role))payload.role='Author';payload.active=true}const x=await repo.create(key,payload);if(key==='posts'&&x.status==='published')emit('blog-published',x).catch(()=>{});if(key==='users')emit('user-registered',{name:x.name,email:x.email}).catch(()=>{});const{password,...safe}=x;res.status(201).json(safe)}));app.put(`/api/${route}/:id`,auth,asyncRoute(async(req,res)=>{if(!writeRoles.includes(req.user.role)){const old=await repo.one(key,req.params.id);if(key!=='posts'||old?.authorId!==req.user.id)return res.status(403).json({error:'Not allowed'});}const changes={...req.body};if(key==='users'){delete changes.password;if(changes.role&&!['Super Admin','Editor','Author'].includes(changes.role))return res.status(400).json({error:'Invalid role'})}const x=await repo.update(key,req.params.id,changes);if(!x)return res.status(404).json({error:'Not found'});if(key==='posts'&&x.status==='published')emit('blog-published',x).catch(()=>{});const{password,...safe}=x;res.json(safe)}));app.delete(`/api/${route}/:id`,auth,asyncRoute(async(req,res)=>{if(!writeRoles.includes(req.user.role)){const old=await repo.one(key,req.params.id);if(key!=='posts'||old?.authorId!==req.user.id)return res.status(403).json({error:'Not allowed'});}await repo.del(key,req.params.id);res.json({ok:true})}))}
resource('pages','pages');resource('posts','posts',['Super Admin','Editor','Author']);resource('categories','categories');resource('users','users',['Super Admin']);
app.get('/api/leads',auth,role('Super Admin','Editor'),asyncRoute(async(req,res)=>res.json(await repo.all('contacts'))));
app.get('/api/public/pages',asyncRoute(async(req,res)=>res.json((await repo.all('pages')).filter(x=>x.status==='published'))));app.get('/api/public/posts',asyncRoute(async(req,res)=>res.json((await repo.all('posts')).filter(x=>x.status==='published'||(x.status==='scheduled'&&new Date(x.publishAt)<=new Date())))));app.get('/api/public/posts/:slug',asyncRoute(async(req,res)=>{const p=(await repo.all('posts')).find(x=>x.slug===req.params.slug&&x.status==='published');if(!p)return res.status(404).json({error:'Post not found'});await repo.update('posts',p._id,{views:(p.views||0)+1});res.json(p)}));
app.post('/api/contact',rateLimit({windowMs:60000,max:12}),asyncRoute(async(req,res)=>{const{name,email,message}=req.body;if(!name||!/^\S+@\S+\.\S+$/.test(email||'')||!message)return res.status(400).json({error:'Name, valid email and message are required'});const x=await repo.create('contacts',req.body);emit('contact-submission',x).catch(()=>{});res.status(201).json({ok:true,message:'Thanks — your message has been received.'})}));
const upload=multer({storage:multer.diskStorage({destination:(r,f,cb)=>cb(null,path.resolve(base,'../uploads')),filename:(r,f,cb)=>cb(null,Date.now()+'-'+f.originalname.replace(/[^a-zA-Z0-9._-]/g,'_'))}),limits:{fileSize:8*1024*1024},fileFilter:(r,f,cb)=>cb(null,f.mimetype.startsWith('image/'))});await fs.mkdir(path.resolve(base,'../uploads'),{recursive:true});app.get('/api/media',auth,asyncRoute(async(req,res)=>res.json(await repo.all('media'))));app.post('/api/media',auth,role('Super Admin','Editor'),upload.single('file'),asyncRoute(async(req,res)=>{if(!req.file)return res.status(400).json({error:'Choose an image file (max 8MB)'});res.status(201).json(await repo.create('media',{filename:req.file.filename,url:'/uploads/'+req.file.filename,mimetype:req.file.mimetype,size:req.file.size,alt:req.body.alt||''}))}));app.delete('/api/media/:id',auth,role('Super Admin','Editor'),asyncRoute(async(req,res)=>{const m=await repo.one('media',req.params.id);if(m){await fs.rm(path.resolve(base,'../uploads',m.filename),{force:true});await repo.del('media',m._id)}res.json({ok:true})}));
app.get('/api/automations',auth,asyncRoute(async(req,res)=>res.json(await repo.all('logs'))));app.post('/api/automations/test',auth,role('Super Admin'),asyncRoute(async(req,res)=>{const l=await emit('contact-submission',{test:true,at:new Date()});res.json({connected:!!process.env.N8N_BASE_URL,status:l.status,result:l.result||l.error,log:l})}));app.get('/api/settings',auth,asyncRoute(async(req,res)=>res.json({demoMode:process.env.DEMO_MODE!=='false',n8nConfigured:!!process.env.N8N_BASE_URL,geminiConfigured:!!process.env.GEMINI_API_KEY,settings:await repo.all('settings')})));app.put('/api/settings',auth,role('Super Admin'),asyncRoute(async(req,res)=>{const s=await repo.all('settings');for(const[key,value]of Object.entries(req.body)){const old=s.find(x=>x.key===key);old?await repo.update('settings',old._id,{value}):await repo.create('settings',{key,value})}res.json({ok:true})}));
app.get('/api/analytics',auth,asyncRoute(async(req,res)=>{const [pages,posts,users,contacts,logs]=await Promise.all(['pages','posts','users','contacts','logs'].map(k=>repo.all(k)));res.json({pages:pages.length,published:posts.filter(x=>x.status==='published').length,drafts:posts.filter(x=>x.status==='draft').length,users:users.length,submissions:contacts.length,runs:logs.length,views:posts.reduce((n,p)=>n+(p.views||0),0),weekly:[{day:'Mon',views:30},{day:'Tue',views:45},{day:'Wed',views:38},{day:'Thu',views:62},{day:'Fri',views:55},{day:'Sat',views:73},{day:'Sun',views:68}]})}));
app.post('/api/ai/generate',auth,asyncRoute(async(req,res)=>{const prompt=String(req.body.prompt||'').slice(0,2000),type=req.body.type||'section';if(!prompt)return res.status(400).json({error:'Enter a prompt'});if(process.env.GEMINI_API_KEY){try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${process.env.GEMINI_API_KEY}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:`Return JSON only with heading, description, cta, seoTitle, metaDescription, content. Task (${type}): ${prompt}`}]}]})});const j=await r.json(),raw=j.candidates?.[0]?.content?.parts?.[0]?.text;return res.json({demo:false,result:JSON.parse(raw.replace(/```json|```/g,''))})}catch(e){console.error('Gemini fallback:',e.message)}}res.json({demo:true,result:{heading:type==='blog'?'Ideas worth sharing':'A better way to build your online presence',description:`${prompt} Turn your next idea into a clear, compelling experience with a team that keeps things simple.`,cta:'Let’s get started',seoTitle:`${prompt.slice(0,45)} | FlowCMS`,metaDescription:`Discover how ${prompt.slice(0,100)} can help your business grow.`,content:`# ${prompt}\n\nGreat work starts with a clear idea. We bring strategy, creativity and practical expertise together to make it real.`}})}));
app.post('/api/webhooks/n8n/:action',asyncRoute(async(req,res)=>{const expected=process.env.N8N_WEBHOOK_SECRET||'local-flowcms-secret';if(req.headers['x-flowcms-secret']!==expected)return res.status(401).json({error:'Invalid webhook secret'});const allowed=['contact-submission','blog-published','user-registered'];if(!allowed.includes(req.params.action))return res.status(404).json({error:'Unknown event'});const l=await log(req.params.action,'n8n callback',JSON.stringify(req.body),'Success');res.json({ok:true,logId:l._id})}));
app.post('/api/internal/publish-scheduled',asyncRoute(async(req,res)=>{if(req.headers.authorization!==`Bearer ${process.env.CMS_SCHEDULE_TOKEN||'local-schedule-token'}`)return res.status(401).json({error:'Invalid schedule token'});const due=(await repo.all('posts')).filter(p=>p.status==='scheduled'&&new Date(p.publishAt)<=new Date());for(const p of due){await repo.update('posts',p._id,{status:'published'});await log('Scheduled Publishing','Cron',`Published: ${p.title}`);emit('blog-published',p).catch(()=>{})}res.json({published:due.length})}));
app.get('/api/health',(req,res)=>res.json({ok:true,database:mongoReady?'mongodb':'demo-json',demoMode:process.env.DEMO_MODE!=='false'}));
app.use((err,req,res,next)=>{console.error(err);res.status(err.status||500).json({error:err.message||'Unexpected server error'})});

if (process.env.VERCEL !== '1') {
  app.listen(port, () => console.log(`FlowCMS API listening on ${port}`));
}
export default app;